# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/WuTa0209"

[social.params]
icon = "brand-github"

[[social]]
identifier = "ITHome"
name = "ITHome"
url = "https://ithelp.ithome.com.tw/users/20138181"

[social.params]
icon = "brand-twitter"
